version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/receipt-processor-challenge  # Mount the local directory to /receipt-processor-challenge in the container
    environment:
      - PYTHONUNBUFFERED=1  # To avoid buffering in logs
    restart: always